#!/usr/bin/env python
"""
 Parses command line and run and plot all releases of a single fire.
 """

from gigatraj import GIGATRAJ, run_cmd

from concurrent.futures import ThreadPoolExecutor, as_completed
import subprocess


def plot_allfires(gt):
    """
    Plots all fires in parallel as separate processes since Matplotlib/cartopy
    are not exactly thread safe.
    """

    # Get a list of fires
    # -------------------
    Fires = []
    for r in gt.cf['Trajectories']['Releases']:
        Fires += r['Fires']
    Fires = sorted(list(set(Fires))) # unique list of Fires

    print(f"Fires to plot: {', '.join(Fires)}")
    
    # Create a list of commands
    # -------------------------
    Cmd = []
    for fire in Fires:
        Cmd += [ f"plot_onefire {fire}", ]

    # Concurrent Run
    # --------------
    maxConcurrent = gt.cf['Trajectories']['MaxConcurrent']
    with ThreadPoolExecutor(max_workers=maxConcurrent) as executor:

        futures = [executor.submit(run_cmd, cmd) for cmd in Cmd]

        for future in as_completed(futures):

            try:
                cmd, stdOut = future.result()
                if gt.Verbose:
                    print('[] '+cmd,'\n',stdOut)

            except subprocess.CalledProcessError as error:
                print(f"Command failed: {error}")

            except Exception as error:
                print(f"Unexpected error: {error}")

    print("All done.")

                
if __name__ == "__main__":

    gt = GIGATRAJ()

    # Initialize trajectories
    # -----------------------
    if gt.Verbose:
        print('[] Initializing parcels...')
    gt.genParcels()

    # Run trajectories
    # ----------------
    if gt.Verbose:
        print('[] Running trajectories in parallel...')
    gt.genTrajectories()

    # Plot all trajectories
    # ---------------------
    if gt.Verbose:
        print('[] Plotting trajectories in parallel...')
    plot_allfires(gt)
    
