#
#  Python cover to Gigatraj Trajectory model (written in C++)
#

import numpy as np
import os
import yaml

from datetime import datetime, timedelta

class TRAJError(Exception):
    """
    Defines general exception errors.
    """
    def __init__(self, value):
        self.value = value
    def __str__(self):
        return repr(self.value)

class GIGATRAJ(object):

    def __init__(self,config='gigatraj.yaml'):
        """
        Initialize Gigatraj. 
        """

        with open("gigatraj.yaml", encoding="utf-8") as stream:
            self.cf = yaml.safe_load(stream)

    def genParcels(self):
        """
        Generate parcels around each fire to start trajectories from.
        """

        cf, F, P, T = self.cf, self.cf['Fires'], self.cf['Parcels'], self.cf['Trajectories']

        # Create list of fires being released
        # -----------------------------------
        fires = []
        for r in cf['Trajectories']['Releases']:
                fires += r['Fires']
 
        # Create parcels for each unique fire
        # -----------------------------------
        for f in list(dict.fromkeys(fires)):

            lon, lat, dz = F[f]['lon'], F[f]['lat'], P['Vdelta_km']
            
            for z in F[f]['altitudes_km']:

                filename = f"{cf['SCRATCH']}/parcels.{f}.{z}km.nc" # omitting release time

                zlow, zhigh = z - dz/2, z + dz/2
            
                cmd = f"{cf['PREFIX']}/bin/gt_generate_parcels --random " + \
                      f" --clat {lat} --clon {lon} "     + \
                      f" --zlow {zlow} --zhigh {zhigh} " + \
                      f" --number {P['Number']} " + \
                      f" --radius {P['Radius_km']} --vertical {P['Vertical']} --vunits {P['Vunits']} " + \
                      f" --format {P['Format']} --netcdf {filename}"

                print(cmd+'\n')
                if os.system(cmd):
                    raise TRAJError('Could not generate parcels.')
            
    def genTrajectories(self):
        """
        Generate Trajectories given parcels on files generated by genParcels().
        """

        cf, F, P, T = self.cf, self.cf['Fires'], self.cf['Parcels'], self.cf['Trajectories']

        # Loop over parcel releases
        # -------------------------
        for R in cf['Trajectories']['Releases']:

            Start, ZeroTime = R['Start'], R['Start']
            Stop = Start + timedelta(days=T['Duration_days'])
            timestep = T['Timestep_min']
            source = T['MetSource']
            MetSpec = f"ModelRun={T['ForecastCycle']}"

            dirname = f"{cf['INSPYRE']}/{T['ForecastCycle']}"
            if os.system(f"mkdir -p {dirname}"):
                raise TRAJError(f"Could not create directory {dirname}")

            # Create parcels for each unique fire
            # -----------------------------------
            for f in R['Fires']:

                for z in F[f]['altitudes_km']:

                    parcels = f"{cf['SCRATCH']}/parcels.{f}.{z}km.nc" # omitting release time 
                    filename = f"{dirname}/trajs.{T['ForecastCycle']}.{f}.{Start.isoformat()}_{z}km.nc"
                
                    cmd = f"{cf['PREFIX']}/bin/gtmodel_s01 --verbose" +\
                          f" --begdate {Start.isoformat()} --enddate ${Stop.isoformat()}" +\
                          f" --zerodate {ZeroTime.isoformat()}" +\
                          f" --tstep {timestep}" +\
                          f" --source {source}" + \
                          f" --metoptions {MetSpec}" + \
                          f" --vertical {T['VTrace']}" +\
                          f" --parcels {parcels}" +\
                          f" --parcelvertical  {P['Vertical']}" +\
                          f" --input_netcdf " + \
                          f" --frequency {T['outFreq_hour']}" + \
                          f" --netcdf_out {filename}" \
                          f" --format \'{T['OutFormat']}\'"

                    print(cmd+'\n')
                    if os.system(cmd):
                        raise TRAJError('Could not generate trajectories.')
                    
#-----

if __name__ == "__main__":

    gt = GIGATRAJ()
    
